# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Will Ricketts
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software engineer, maker of awesome things, explorer, musician, lover of food 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://willricketts.com" # the base hostname & protocol for your site
twitter_username: willricketts
github_username:  willricketts

# Build settings
markdown: kramdown
